modified:   Makefile 	modified:   README.md 	modified:   common/quaternion_utils.cpp 	modified:   common/quaternion_utils.hpp
	fixed this compile time error

In file included from /usr/include/glm/gtx/quaternion.hpp:21,
                 from common/quaternion_utils.cpp:5:
/usr/include/glm/gtx/norm.hpp:21:3: error: #error "GLM: GLM_GTX_norm is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
 # error "GLM: GLM_GTX_norm is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
   ^~~~~

	by adding this to both utils files